// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Wbf3rziojjyszAwqtz3Z_7csRsKUWqI',
    appId: '1:17153289666:web:a0418b76cbf34fc12e7a5b',
    messagingSenderId: '17153289666',
    projectId: 'demoproject-1173b',
    authDomain: 'demoproject-1173b.firebaseapp.com',
    storageBucket: 'demoproject-1173b.firebasestorage.app',
    measurementId: 'G-PZQ7BHF3N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs0HMVJJmWedEjOE0O6il5zZoZns-6ySM',
    appId: '1:17153289666:android:25d6d611fdd7eb742e7a5b',
    messagingSenderId: '17153289666',
    projectId: 'demoproject-1173b',
    storageBucket: 'demoproject-1173b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBINyoZa08EAlpOW6Db5OXXnN7khg_u9j0',
    appId: '1:17153289666:ios:882e8bcfaa6dbd392e7a5b',
    messagingSenderId: '17153289666',
    projectId: 'demoproject-1173b',
    storageBucket: 'demoproject-1173b.firebasestorage.app',
    iosBundleId: 'com.example.demoproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBINyoZa08EAlpOW6Db5OXXnN7khg_u9j0',
    appId: '1:17153289666:ios:882e8bcfaa6dbd392e7a5b',
    messagingSenderId: '17153289666',
    projectId: 'demoproject-1173b',
    storageBucket: 'demoproject-1173b.firebasestorage.app',
    iosBundleId: 'com.example.demoproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_Wbf3rziojjyszAwqtz3Z_7csRsKUWqI',
    appId: '1:17153289666:web:efed483c1ad982892e7a5b',
    messagingSenderId: '17153289666',
    projectId: 'demoproject-1173b',
    authDomain: 'demoproject-1173b.firebaseapp.com',
    storageBucket: 'demoproject-1173b.firebasestorage.app',
    measurementId: 'G-VCZ3C4TQ82',
  );
}
